### ISSUE TITLE
SimplyDarkDiscord-Gray: Slowmode icon gets overlapped

### ISSUE THREAD

**Issue by justalemon** [Gibbu/BetterDiscord-Themes#1]
After installing SimplyDarkDiscord on the gray edition, the Slowmode text gets moved to the top and the icon ends up being overlapped by the member list.

![image](https://user-images.githubusercontent.com/11861253/50205918-a9a1e980-0348-11e9-82c3-07123e989d5f.png)

All of the other themes and scripts have been disabled, so is specific for this theme.

**Comment by Gibbu** [comment]
I didn't even know that Discord had a slow mode. Sorry about that

**Comment by justalemon** [comment]
Yep, is fixed.
![image](https://user-images.githubusercontent.com/11861253/50240306-2f528300-03a3-11e9-81af-82f64ae04747.png)
Thanks!
