### ISSUE TITLE
[SDD] "You're viewing older messages" box, when clicked, changes shape and breaks text

### ISSUE THREAD

**Issue by HalfOfAKebab** [Gibbu/BetterDiscord-Themes#10]
Normally, the box looks normal, but when I click it, this happens:
![sdd](https://user-images.githubusercontent.com/23153864/55255267-17b45180-5252-11e9-8472-4088be41ce2e.png)

**Comment by Gibbu** [comment]
Hey man sorry I took so long. Was really busy on other things. I've fixed this :)
