### ISSUE TITLE
[SDD] Some elements are missing background colour

### ISSUE THREAD

**Issue by HalfOfAKebab** [Gibbu/BetterDiscord-Themes#13]
Some elements are missing a background fill colour, making them hard to read in some instances

![Capture](https://user-images.githubusercontent.com/23153864/57274283-b7a39d00-7092-11e9-96b8-c6d38d209251.PNG)
![Capture2](https://user-images.githubusercontent.com/23153864/57274284-b7a39d00-7092-11e9-9260-6b4ae3687d48.PNG)
![Capture3](https://user-images.githubusercontent.com/23153864/57274285-b83c3380-7092-11e9-88f4-31ddf650aecb.PNG)

**Comment by Gibbu** [comment]
Sorry about that, redownload the SimplyDarkDiscord.theme.css

**Comment by HalfOfAKebab** [comment]
Thanks, but now I'm getting a compile error and can't use SDD at all lol:

SimplyDarkDiscord-Dark.theme.css
Could not be compiled.
META was not found.

**Comment by Gibbu** [comment]
Here's an updated link that works for me. So it should work for you
https://betterdiscord.net/ghdl?id=2887

**Comment by HalfOfAKebab** [comment]
Works now, thanks
