### ISSUE TITLE
Small guilds

### ISSUE THREAD

**Issue by MinerChAI** [Gibbu/BetterDiscord-Themes#18]
Compare:
![Without horizontal server list](https://user-images.githubusercontent.com/43097806/60538070-8c47d200-9d12-11e9-91eb-1c41aea525b9.png)
![With](https://user-images.githubusercontent.com/43097806/60538153-aa153700-9d12-11e9-8fc1-ebe9edb60f42.png)
HorizontalServerList is incompatible with Nox

**Comment by Gibbu** [comment]
That is true. Horizontal Server List can only do so much. With just pure CSS I cannot make a theme compatible with another without breaking it for others. You'll need to ask Zerebos to create a Nox version of Horizontal Server List. I would create one but I'm currently busy with other things
