### ISSUE TITLE
SimplyDarkDiscord: "You have unsaved changes" is not centered

### ISSUE THREAD

**Issue by justalemon** [Gibbu/BetterDiscord-Themes#2]
Self explanatory. The text "Careful - you have unsaved changes!" is not centered.

![image](https://user-images.githubusercontent.com/11861253/50736850-5087e180-11a1-11e9-8d11-3a8e548c7c78.png)

I see two options here:
1. Make it centered
2. Extend the bar so it goes from side to side

**Comment by Gibbu** [comment]
I see, I might do the 2nd option.
Makes it look "different".

**Comment by Gibbu** [comment]
Alright, should be fixed.

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/50748196-ead63c80-1216-11e9-9c0e-aba4a33571c9.png)
Yep, now it looks good.
