### ISSUE TITLE
TrueLight

### ISSUE THREAD

**Issue by salasan1** [Gibbu/BetterDiscord-Themes#21]
Light works but emoji box is still dark.

**Comment by Gibbu** [comment]
You possibly have BetterDiscord Dark Mode enabled. TrueLight doesn't touch the emojipicker.
If you're not talking about this can you screenshot that area that you're talking about?

**Comment by salasan1** [comment]
I mean that emojipicker

**Comment by Gibbu** [comment]
Like I said. TrueLight doesn't touch the Emojipicker apart from the scrollbar colour.
To disable Discord dark mode `User Settings → Settings → Dark Mode`

![image](https://user-images.githubusercontent.com/20338746/62848821-7c170f80-bd20-11e9-81da-39c5c6ecb807.png)
