### ISSUE TITLE
Triple dot options on messages.

### ISSUE THREAD

**Issue by Kakarifers** [Gibbu/BetterDiscord-Themes#25]
So when the theme is enabled the boxes for these are a tad too large. Only three of the five options will show for me. Is there any way to shrink how large these appear when opening that menu?

**Comment by Gibbu** [comment]
Paste this at the very end/bottom of `FrostedGlass.theme.css`
```css
#app-mount .container-3cGP6G .item-2J1YMK {
    padding: 5px 10px;
}
```
Decreasing the `5px` will make each button smaller in height and decreasing the `10px` will make each button smaller in width.

**Comment by Kakarifers** [comment]
Tried that. Didn't change anything when making both values 1px. Still looked as such on the bottom most message: https://i.imgur.com/M52mh7n.png

**Comment by Gibbu** [comment]
🤔 That's weird, it works for me.
This is my current file:
![image](https://user-images.githubusercontent.com/20338746/63404620-3ac0e700-c427-11e9-986c-b8d9305a21ee.png)

**Comment by Kakarifers** [comment]
https://i.imgur.com/8yV5aHC.png
https://i.imgur.com/ey6wQOw.png
Ditto.

**Comment by Gibbu** [comment]
I think it's because you didn't add `!important` to the end. Like so:
```css
#app-mount .container-3cGP6G .item-2J1YMK {
    padding: 5px 10px !important;
}
```

**Comment by Kakarifers** [comment]
Added. Still the same issue. Not sure why. It only affects the bottom most message. Which if you need to delete it makes things a hassle.

**Comment by Gibbu** [comment]
Can you send me your `FrostedGlass.theme.css` file?

If we can't figure this out I highly recommend Message Utilities by DevilBro. It allows for quick deleting messages by holding down `Delete` and the  clicking. Download: https://betterdiscord.net/ghdl?id=1058.

**Comment by Kakarifers** [comment]
[FrostedGlass.theme.zip](https://github.com/Gibbu/BetterDiscord-Themes/files/3527931/FrostedGlass.theme.zip)

**Comment by satoru8** [comment]
@Kakarifers 
99% sure I see the issue. Try this. 

[FrostedGlass.theme.css.zip](https://github.com/Gibbu/BetterDiscord-Themes/files/3528000/FrostedGlass.theme.css.zip)

**Comment by Kakarifers** [comment]
Nope. Same issue. Bottom most message cuts off. Seems to be related to the cutoff point of the Discord window itself.

**Comment by Kakarifers** [comment]
So it knows there is another option below the third one, but I just can't see it. Doesn't float the choices upwards on that lowest message.

**Comment by Kakarifers** [comment]
Turn off the theme and it works just as you'd expect it to.

**Comment by satoru8** [comment]
Oh, I see. That doesn't happen in my discord at all, even with the theme.
Kind of hard to fix the issue when I can't reproduce it. 
You can try this and if it doesn't work then add a scroller to it using the 2nd code block. 

`Relative position instead of absolute`
```css
#app-mount .container-3cGP6G {
    position: relative
}
```

`Add scrollbar to context menu`
```css
#app-mount .container-3cGP6G {
    overflow-y:scroll;
    height:100px
}

**Comment by Kakarifers** [comment]
First code block worked flawlessly. Thanks!

**Comment by satoru8** [comment]
okay, good, then i can let gibbu know what the issue is.
