### ISSUE TITLE
Server banner does not work in Frosted Glass

### ISSUE THREAD

**Issue by RikuKawai** [Gibbu/BetterDiscord-Themes#26]
The server banner does not display in the FrostedGlass theme, see below
![image](https://user-images.githubusercontent.com/13458480/64647672-70823b80-d3e7-11e9-8d87-243c9c7cbb6a.png)
Expected behaviour in the default theme below
![image](https://user-images.githubusercontent.com/13458480/64647733-8f80cd80-d3e7-11e9-9ac7-4a482557e9e5.png)

I think the server banner was recently changed in the new Discord update which is likely the culprit.

**Comment by Gibbu** [comment]
Fixed :)
