### ISSUE TITLE
Frosted glass Activity card background not transparent and background image flashes black time to time

### ISSUE THREAD

**Issue by Jaminator827** [Gibbu/BetterDiscord-Themes#29]

**Comment by Gibbu** [comment]
I just updated my themes for the new update.

With the image flashing time to time that's an issue with Electron and css variables with image urls.
To fixed this paste this code [(pastebin)](https://pastebin.com/raw/iejY6gM0) at the very bottom/end of your `FrostedGlass.theme.css` file. If you use a different image to the default simply replace `https://i.imgur.com/kYW2H5C.jpg` with your image url.
