### ISSUE TITLE
SimplyDarkDiscord: Impossible to see the invite link when joining a server

### ISSUE THREAD

**Issue by justalemon** [Gibbu/BetterDiscord-Themes#3]
![image](https://user-images.githubusercontent.com/11861253/50831544-f0707700-1329-11e9-9295-d5dc0b8762fb.png)

Gray theme by the way.

**Comment by Gibbu** [comment]
Fixed

**Comment by justalemon** [comment]
Yep, now is fixed.
![image](https://user-images.githubusercontent.com/11861253/51071411-392c7680-162f-11e9-9abf-6fc664ef3c2e.png)

PD: As the repo owner, you can close the issues once you fix them.
