### ISSUE TITLE
In Frosted Glass, scrolling in pop out causes roles to become misaligned with their background

### ISSUE THREAD

**Issue by MithicSpirit** [Gibbu/BetterDiscord-Themes#31]
In Frosted Glass, when scrolling in the user pop out, which is enabled when the user has too many roles, it causes the "background" of each role to become vertically misaligned from the "outline" of the role, many times even going into another role's outline.

This only occurs when [this plugin](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/PermissionsViewer) is active (I will also open an issue there). 
![Annotation 2019-10-22 181732](https://user-images.githubusercontent.com/24192522/67339124-8f044800-f4f8-11e9-8ed5-7ecbb95585ae.png)

**Comment by MithicSpirit** [comment]
[Link to issue in their github](https://github.com/rauenzi/BetterDiscordAddons/issues/183)

**Comment by Gibbu** [comment]
That was a weird bug but I managed to fix it!
You can close the issue on Zerebos' Github as well :)
