### ISSUE TITLE
Embeds and emoji menu broken by Discord update

### ISSUE THREAD

**Issue by RikuKawai** [Gibbu/BetterDiscord-Themes#32]
Recent Discord update has broken the styling for embeds and the emoji menu, as shown below.

![image](https://user-images.githubusercontent.com/13458480/68787738-16346f80-0610-11ea-9caf-58d6571ee944.png)

![image](https://user-images.githubusercontent.com/13458480/68787811-3b28e280-0610-11ea-840d-d5d80ff37d17.png)

![image](https://user-images.githubusercontent.com/13458480/68787972-7c20f700-0610-11ea-9294-9fb60570f564.png)

**Comment by Gibbu** [comment]
Ah. I forgot about the emoji picker :\

**Comment by Gibbu** [comment]
Fixed.
