### ISSUE TITLE
Frosted Glass Problem

### ISSUE THREAD

**Issue by Jaminator827** [Gibbu/BetterDiscord-Themes#34]
![Capture](https://user-images.githubusercontent.com/55116936/71297101-f0993500-2336-11ea-9aff-b3349bab792c.PNG)
 The message bar at the bottom of the screen is not transparent.

**Comment by MasicoreLord** [comment]
Known issue, Discord did some update to the text area yet again.
Give theme and plugin devs time to sort it out.

Shouldn't take too long though (at least for themes), as it's just different class name(s).

**Comment by Gibbu** [comment]
Fixed
