### ISSUE TITLE
Frosted Glass - Friends/Activity menu broken by update

### ISSUE THREAD

**Issue by RikuKawai** [Gibbu/BetterDiscord-Themes#38]
The new friends/activity screen isn't themed.
![image](https://user-images.githubusercontent.com/13458480/73421570-4ed11480-42f4-11ea-8249-bd7e2af443f4.png)

**Comment by Gibbu** [comment]
Known. Will check if I've got the update when I get home.

**Comment by Gibbu** [comment]
Fixed
