### ISSUE TITLE
SimplyDarkDiscord: "User is typing..." text gets really huge

### ISSUE THREAD

**Issue by justalemon** [Gibbu/BetterDiscord-Themes#4]
![image](https://user-images.githubusercontent.com/11861253/50835987-da1ce800-1336-11e9-8520-3f2843568b2d.png)

**Comment by justalemon** [comment]
> Are you able to send the code?
> A possible fix?
Sadly no, CSS is not my stuff.

What is going on here is that when a user starts typing, the three dots get really huge plus the text is moved to the right and shortened.

**Comment by Gibbu** [comment]
>Sadly no, CSS is not my stuff.
That's all good. But I'm still not able to get this problem.
Do you have any other themes that might conflict this theme?

**Comment by justalemon** [comment]
The only thing installed is SimplyDarkDiscord, so no there is nothing that might be colliding with the theme.

**Comment by Gibbu** [comment]
I see the problem. You got a Discord update before me. I've just got the changes and fixed them.
