### ISSUE TITLE
Frosted Glass Theme Sometimes Flashes Black Again 

### ISSUE THREAD

**Issue by Jaminator827** [Gibbu/BetterDiscord-Themes#40]
It kind of looks like it is reloading the discord or theme and flashes black for a split second then reverts back to normal. This is the second time a problem has occurred and it still persists after fixing it once by pasting some extra code in the css file

**Comment by UPPERCASEuser** [comment]
It isnt a theme issue. Probally a plugin issue

**Comment by Jaminator827** [comment]
I'm not using any plugins though, so I'm not sure what else can be a prob

**Comment by Gibbu** [comment]
You have already asked this question before. Read #29

**Comment by Jaminator827** [comment]
Yes sorry ik i have asked this, but the fix is no longer working

**Comment by Gibbu** [comment]
Hmmm, try this [https://hastebin.com/ukuxafovoy.css](https://hastebin.com/ukuxafovoy.css)

**Comment by Jaminator827** [comment]
I'll check it out

**Comment by Jaminator827** [comment]
Still doesn't work. Im using FrostedGlass.theme, HorizontalServerlist.theme, and RadialStatus.theme btw

**Comment by Gibbu** [comment]
Frosted Glass is currently getting a rework.
The rework will use the new `backdrop-filter` rule and Discord inbuilt css variables to reduce code size.
So I'm pretty much stopped working on the current Frosted Glass unless a major change happens.

You can view and download the new Frosted Glass here: https://github.com/GibbuBDStuff/FrostedGlass
