### ISSUE TITLE
The thumbnail in the image/file upload modal is cropped

### ISSUE THREAD

**Issue by aCluelessDanny** [Gibbu/BetterDiscord-Themes#41]
When you upload an image or file to Discord, the modal pops in as normal, but the thumbnail of that image (or the placeholder for other files) is cropped.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/21282515/75038686-7bec8f00-547c-11ea-882d-0f15aadba69a.png">

Looking into the CSS, the `overflow: hidden` rule on the modal is what's cropping it. I see you use this for the blurred background too, so you could either find a way to override the `overflow` rule for the thumbnail or reposition the thumbnail to be completely within the modal.

_Also unrelated issue, but the bottom bar of the modal is also an unstyled grey color_

**Comment by Gibbu** [comment]
Frosted Glass is currently getting a rework.
The rework will use the new `backdrop-filter` rule and Discord inbuilt css variables to reduce code size.
So I'm pretty much stopped working on the current Frosted Glass unless a major change happens.

You can view and download the new Frosted Glass here: https://github.com/GibbuBDStuff/FrostedGlass
