### ISSUE TITLE
Picture, message box, link preview position not correct

### ISSUE THREAD

**Issue by LoYungSum** [Gibbu/BetterDiscord-Themes#43]
All things are shifted to the left
Image
![image](https://user-images.githubusercontent.com/25066078/75444304-2b09f880-599e-11ea-8d7c-9cc2d48af453.png)
Link Preview
![image](https://user-images.githubusercontent.com/25066078/75444367-4412a980-599e-11ea-9b37-33e207ce17bf.png)
Message box
![image](https://user-images.githubusercontent.com/25066078/75444469-71f7ee00-599e-11ea-982a-a4ca4d81942e.png)

**Comment by Gibbu** [comment]
Re-enable the theme.

**Comment by LoYungSum** [comment]
Thanks. It work now
