### ISSUE TITLE
RadialStatus completely changes the look of Discord as of today

### ISSUE THREAD

**Issue by wefalltomorrow** [Gibbu/BetterDiscord-Themes#44]
GIF demonstration: https://i.imgur.com/GP7HK68.gif

**Comment by Gibbu** [comment]
Oh woops. Try now?

**Comment by Tropix126** [comment]
Nice one

**Comment by wefalltomorrow** [comment]
[**@Gibbu**](https://github.com/Gibbu) commented on [4 Mar 2020, 15:22 GMT+11](https://github.com/Gibbu/BetterDiscord-Themes/issues/44#issuecomment-594318998 "2020-03-04T04:22:50Z - Replied by Github Reply Comments"):
> Oh woops. Try now?

Works now, thanks!
