### ISSUE TITLE
[Bug/Feature] Radialstatus

### ISSUE THREAD

**Issue by barbiehunter** [Gibbu/BetterDiscord-Themes#47]
Why is the avater now not Round anymore? i dont like it so right now....  pls make a option to change the design or something.
![image](https://user-images.githubusercontent.com/38357837/76161377-52e22480-6133-11ea-9211-7aaa33d27949.png)

**Comment by wefalltomorrow** [comment]
Same issue here.

**Comment by Gibbu** [comment]
I've recently moved the base css to a different repo. Which can be found here: https://github.com/GibbuBDStuff/RadialStatus

Redownload link: https://betterdiscord.net/ghdl?id=3149

**Comment by wefalltomorrow** [comment]
[**@Gibbu**](https://github.com/Gibbu) commented on [9 Mar 2020, 11:38 GMT+11](https://github.com/Gibbu/BetterDiscord-Themes/issues/47#issuecomment-596273003 "2020-03-09T00:38:28Z - Replied by Github Reply Comments"):
> I've recently moved the base css to a different repo. Which can be found here: [https://github.com/GibbuBDStuff/RadialStatus](https://github.com/GibbuBDStuff/RadialStatus)
> 
> Redownload link: [https://betterdiscord.net/ghdl?id=3149](https://betterdiscord.net/ghdl?id=3149)

Thanks!
