### ISSUE TITLE
Horizontal Server List Problem

### ISSUE THREAD

**Issue by Svenskithesource** [Gibbu/BetterDiscord-Themes#49]
When I activate Horizontal Server List this happens
![image](https://user-images.githubusercontent.com/40274381/78135078-89088080-7421-11ea-9df2-863032d82273.png)

**Comment by Gibbu** [comment]
I am aware of the issue and will try figure out a fix. For now I guess just place your servers in folders or just disable it for now.

**Comment by Gibbu** [comment]
Re-enable the theme now and it should be better but not what it used to be
