### ISSUE TITLE
Discord Moving

### ISSUE THREAD

**Issue by YasherK** [Gibbu/BetterDiscord-Themes#5]
When I use this css file into my themes, when i want to drag over discord to my second monitor, It doesn't allow me. I am not sure why this happens, but if there is an updated css file that I could use, I would appreciate it if someone linked me that. I really like this theme.

**Comment by Gibbu** [comment]
Drag the *NAME*.theme.css file into your `C:\Users\USER\AppData\Roaming\BetterDiscord\themes`

If that is not there you'll need to install BandagedBetterDiscord.
Steps on installing themes and plugins https://www.betterdiscordlibrary.com/install

**Comment by YasherK** [comment]
I actually figured it out. When I use this theme, I have to click the very very top of the window in order to drag it. I wish there was a way to make the selection bigger. When Discord is in full screen, I have to move my mouse to the VERY TOP of my monitor and click and drag to move it. I was just asking if there was a way to make the selection a bit bigger. I really like the theme. If you created this, props to you.
