### ISSUE TITLE
Background Image cannot be overruled

### ISSUE THREAD

**Issue by just-Addict** [Gibbu/BetterDiscord-Themes#51]
Sooo, I saw a preview of the FrostedGlass theme. and I liked how it shrinks the main display leaving an open space all around.

But, even though the background is a nice looking image, after a while I got bored with it and wanted to use my own images using the TransientBackground plugin.
So I went and commented out the background bit in the CSS file expecting to see the above mentioned plugin do its thing. It did, but only for the flat background, the bit that is shrunk and showing the actual Discord UI still keeps showing the default background image... 

So I took a look inside the base.css file and see that the background image gets redefined there. Don't like that... it prevents dynamic background changing via plugin.

Please change this so I can use the above mentioned plugin to also have it change the background in the shrunked part instead of just the image behind it.

**Comment by ToxxyTheTrash** [comment]
you don't need a plugin to change the background and you were most likely changing the wrong values, didnt save, or discord didn't reload the theme after saving.

use this instead https://gibbu.me/editor/frostedglass

**Comment by Gibbu** [comment]
> Please change this so I can use the above mentioned plugin to also have it change the background in the shrunked part instead of just the image behind it.

I'm not going change how a theme works just for 1 person with a plugin that I've never heard of. Also if you want to change the image, just open the `FrostedGlass.theme.css` fille and change `--BG-image` url link. Or use my theme editor like toxxy said above.

**Comment by just-Addict** [comment]
@ToxxyTheTrash Don't tell me what I do or don't need. I have a working plugin that changes the background, selecting one from a personal predefined collection. Works perfectly as long as a theme is transparent. 
This theme is transparent and allows me to specify a single static background only. 
@Gibbu 
I wasn't asking for all that much, but if you allow users to change the background it's rather one sided to only allow them to use a static background in _your_ theme regardless of the fact a user may already have a method to use a collection of backgrounds that get used in a slideshow style fashion. So since you won't allow for that I've gone and just took the whole thing local and changed it myself.

**Comment by Gibbu** [comment]
> it's rather one sided to only allow them to use a static background in *your* theme

What. I'm guessing your plugin changes the background only for `#app-mount`. This would mean I would have to rework how the entire theme works just for you.

> a user may already have a method to use a collection of backgrounds that get used in a slideshow style fashion.

You're the only person that I have heard using such a plugin, so why would I add support for it?

> So since you won't allow for that I've gone and just took the whole thing local and changed it myself.

You could've just done that from the start...?

**Comment by just-Addict** [comment]
Again, no, assumption is the mother of all FU's, that is just it... It doesn't. Like I said, all that blocked my collection of backgrounds to show _inside the main part of your layout_, because they showed on the layer behind it, was the redefinition of the `--BG-image` in the base CSS... Take out the redefinition and since your theme already takes care of all other transperencies, Dynamically changed backgrounds now show throughout.

But as I already mentioned, you don't have to bother, I'll just nuke that var in a local copy of the base.css file.
