### ISSUE TITLE
Online thingy

### ISSUE THREAD

**Issue by bluhdy** [Gibbu/BetterDiscord-Themes#53]
for how much people is online its like off to the right more how do i make it under the home icon its not working for me
![image](https://user-images.githubusercontent.com/63445072/79169521-47c58880-7db2-11ea-8361-2e141adbcc3f.png)

**Comment by Gibbu** [comment]
I'll check it out

**Comment by Gibbu** [comment]
The plugin is very limiting when it comes to theme customization. But this is the best I could get it.
![image](https://user-images.githubusercontent.com/20338746/80170023-5b7eb380-862a-11ea-961e-455049618345.png)
