### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ViewHideName47** [Gibbu/BetterDiscord-Themes#54]
In general, a huge flaw is the picture in the background, that is, stretching the window is unrealistic for the cant) + there is no slider where the server is

**Comment by Gibbu** [comment]
"stretch the window is unrealistic for the cant"
What does that even mean?

"there is no slider where the server is"
That is how Discord normally is.

Also, if you could provide more information and screenshots rather than, "Bug" and a option that would be nice.
