### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by DiabloSama** [Gibbu/BetterDiscord-Themes#55]
https://prnt.sc/s9cza5
Why are the side bars like that ? 
it doesnt look cool if you could fixed to its original size it would be better in my opinion

**Comment by ToxxyTheTrash** [comment]
whatever you're trying to say, you can always customize the theme on https://gibbu.me/editor/frostedglass.

**Comment by Gibbu** [comment]
You can do what Toxxy suggested as it's makes editing the theme a whole lot easier. Or you just need to open the `FrostedGlass.theme.css` file and change `--BG-window-padding` to `0`.
