### ISSUE TITLE
Unread message bug

### ISSUE THREAD

**Issue by BriceTheBruce** [Gibbu/BetterDiscord-Themes#56]
There is a bug on the display of the red text when a message is unread.
![unread0](https://user-images.githubusercontent.com/49374099/81281891-be287400-905a-11ea-9cf8-dc9ff578ffa2.PNG)
![unread1](https://user-images.githubusercontent.com/49374099/81281900-c08ace00-905a-11ea-8d0c-07ee02f05d8a.PNG)

As you can see, the 2020 and the NEW are attached.

**Comment by Gibbu** [comment]
Fixed
