### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by Declava** [Gibbu/BetterDiscord-Themes#58]
![image](https://user-images.githubusercontent.com/63688300/81599398-5b4a1c00-937d-11ea-85cf-fe99bc5899f9.png)

**Comment by Gibbu** [comment]
Cheers for that very detailed bug report. Can you tell me how you achieved this?

**Comment by Declava** [comment]
I clicked on some random person on the member list and was gonna give him a role then happened to stumble upon it. Just thought I'd submit it.
