### ISSUE TITLE
"[User] is typing..." text covers the bottommost message

### ISSUE THREAD

**Issue by HalfOfAKebab** [Gibbu/BetterDiscord-Themes#6]
The "[User] is typing..." notification covers over the latest message.

**Comment by Gibbu** [comment]
Hm... I don't get this problem, are you able to send over a fix or a screenshot?
![What I get](https://user-images.githubusercontent.com/20338746/54171105-6087ae80-44cd-11e9-8e84-90c9abdae73f.png)

**Comment by HalfOfAKebab** [comment]
Oh, it turns out that it's an issue with compact mode, turning compact mode off makes it look like your screenshot

**Comment by Gibbu** [comment]
Oh, I totally forgot that compact mode was a thing...
That makes sense though, pretty sure compact and normal use different class selectors.

**Comment by Gibbu** [comment]
Should be fixed for compact now.

![image](https://user-images.githubusercontent.com/20338746/54253558-ba5aa800-45a3-11e9-827b-921397c845d7.png)

**Comment by HalfOfAKebab** [comment]
Works perfectly, thanks a lot
