### ISSUE TITLE
[BUG] (FrostedGlass) - (Brief description)

### ISSUE THREAD

**Issue by FoxyTheCuteAqua** [Gibbu/BetterDiscord-Themes#64]
Repeating Custom CSS Editor Detach desk.

After going to settings opening and Detaching Custom CSS editor.

To see the bug 
Go to settings > Custom CSS Editor > Detach it > Go to themes or plugins > Go back to Custom CSS (repeat this some times 'Go to themes or plugins > Go back to Custom CSS' and you'll see duplicated windows of Custom CSS Attach desk.

![image](https://user-images.githubusercontent.com/66118482/83251017-a489d080-a1b1-11ea-8755-f556ffb92f70.png)

Discord channel: Stable
OS: Windows

**Comment by Gibbu** [comment]
This is not a issue of Frosted Glass but a issue with BetterDiscord
