### ISSUE TITLE
the option to use gifs is missing

### ISSUE THREAD

**Issue by RoseBlackBones** [Gibbu/BetterDiscord-Themes#65]
In the text box next to the emoji button the gift nitro and gif button don't seem to be their at all

on windows 10 using the frosted glass theme v2.0.0

**Comment by Gibbu** [comment]
Open your `FrostedGlass.theme.css` file and change `--show-gift-gif-buttons` to `block`.
Like so: `--show-gift-gif-buttons: block;`

**Comment by RoseBlackBones** [comment]
Ah thank you ^.^
