### ISSUE TITLE
SimplyDark - Black roles hard to see messages

### ISSUE THREAD

**Issue by hiviy16562** [Gibbu/BetterDiscord-Themes#66]
If you have coloured messages enabled it's hard to see peoples messages who have black roles without highlighting the message.

**Comment by Gibbu** [comment]
I can't really do anything about this. I would have to add every single "black" that is hard to read.
It would be like this:
```
rgb(0,0,0)
rgb(1,0,0)
rgb(2,0,0)
...
rgb(20,20,20)
```
If that makes sense.

**Comment by hiviy16562** [comment]
thats ok, i thought u might be able to add a range of similar colours or something but thats fine
