### ISSUE TITLE
[BUG] Frosted Glass - Hard to see texts in the new discord "inbox" feature

### ISSUE THREAD

**Issue by seriaati** [Gibbu/BetterDiscord-Themes#67]
**Describe the bug**
Shown in the gif.

**To Reproduce**
Click on the inbox icon in the DM page.

**Screenshots**
![t](https://user-images.githubusercontent.com/61446626/84965557-d0113280-b141-11ea-9225-ac7d0912c10b.gif)

**Desktop (please complete the following information):**
Discord channel: Stable
OS: Windows

**Additional context**
Nothing else.

**Comment by Gibbu** [comment]
Seems like a new Discord update. I'll fix it soon

**Comment by Gibbu** [comment]
Fixed. Also I recommend getting a different GIF screen recorder.
