### ISSUE TITLE
Issue with server member container not matching rest of ui (grey)

### ISSUE THREAD

**Issue by JordansplaceYT** [Gibbu/BetterDiscord-Themes#68]
"Issue with server member container not matching rest of ui (grey)" 

i use powercord -

**Comment by Gibbu** [comment]
Thanks for that very helpful bug report.

Can you give me more details please.
Theme name, what area you're talking about, screenshots.

**Comment by JordansplaceYT** [comment]
Sorry (new to github) 
its minimal cord on powercord - 
the issue is with the member area on servers , its grey instead of a darker black that the rest of the theme uses. 
*mine is slightly customised but its still present on the stock theme- i tested
![image](https://user-images.githubusercontent.com/65009223/85926643-a8843d80-b898-11ea-85a1-fabc2f089e71.png)

**Comment by JordansplaceYT** [comment]
im on windows btw , if that matters i dought it does tho -

**Comment by Gibbu** [comment]
It seems Discord changed a bunch of things. I'll take a look in the morning.

**Comment by Gibbu** [comment]
Ahh I forgot Powercord is on Canary. I try to not update my themes until they get pushed to Stable. This means I don't have to update unnecessary things and waste time as they could just be removed.

**Comment by mr2meowsYT** [comment]
same issue

**Comment by Gibbu** [comment]
Fixed. Re-enable the theme.
