### ISSUE TITLE
[BUG] MinimalCord+HorizantalServerList - Not showing unread icon

### ISSUE THREAD

**Issue by SecurityInsanity** [Gibbu/BetterDiscord-Themes#69]
**Describe the bug**

Recently HorizintalServerList has started not showing the grey dots that show there's unread messages in a channel.

**To Reproduce**

- Install latest Discord Canary + Theme Manager of choice (I've been using powercord).
- Install Horizontal Server Icons
- Wait until a server gets a message
- You'll notice there's no grey dot icon

**Screenshots**

![Image 2020-06-27 at 12 52 25 PM](https://user-images.githubusercontent.com/7262714/85930021-41559180-b876-11ea-957c-2c8a381d637d.png)

(Some of these channels have unread messages, but as you can see there are 0 dots)

**Desktop (please complete the following information):**
Discord channel: Canary
OS: Windows

**Comment by abUwUser** [comment]
the same issue happens with dark theme as well?

**Comment by SecurityInsanity** [comment]
Seems to be yes (I realized I can use the inbox to show there are actually unread messages)

![Notifys](https://user-images.githubusercontent.com/7262714/85931019-461e4380-b87e-11ea-9699-5b6dbcb7f4a5.png)

**Comment by SecurityInsanity** [comment]
Actually this seems to be caused by MinimalCord as removing minimal cord causes them to show up again. Reworking issue name.

**Comment by Gibbu** [comment]
I'll just copy paste what I said in the other issue.

Ahh I forgot Powercord is on Canary. I try to not update my themes until they get pushed to Stable. This means I don't have to update unnecessary things and waste time as they could just be removed.

**Comment by Gibbu** [comment]
Seems to be fixed in the recent update?
![gif](https://user-images.githubusercontent.com/20338746/86147782-26687300-bb3d-11ea-9dd9-514811d80d74.gif)

**Comment by SecurityInsanity** [comment]
Yep, was leaving open just as a tracker for people searching, but yep fixed for me in the most recent update.

Thanks much!
