### ISSUE TITLE
[SimplyDarkDiscord] Very difficult to drag the window

### ISSUE THREAD

**Issue by HalfOfAKebab** [Gibbu/BetterDiscord-Themes#7]
It's really difficult to drag the top of the window to move Discord around. It's only the top 4 pixels or so that you can drag, which makes it a really annoying experience to move Discord between monitors, for example.

**Comment by Gibbu** [comment]
Indeed. If I increase the size more it conflicts with the header buttons (Search, pinned messages, alerts, ect.).
The only problem with having the titlebar hidden.

**Comment by HalfOfAKebab** [comment]
Hmm, yeah. Well, it can definitely be extended a little further than it currently is without interfering with any of the buttons (as far as I can tell). So although a proper fix would be difficult, maybe it would be an acceptable solution to extend it as much as possible? I'd provide code to help but I have no idea how to write CSS.

**Comment by Gibbu** [comment]
Yeah, I'll extend it as far as possible

**Comment by Gibbu** [comment]
I was able to increase it by 4 pixels, but that's the best I can do

**Comment by HalfOfAKebab** [comment]
That's a lot better than it was, thanks
