### ISSUE TITLE
[BUG] (SimplyDark) - (Colours not applying)

### ISSUE THREAD

**Issue by McCheekiBreeki** [Gibbu/BetterDiscord-Themes#71]
**Describe the bug:**
For some elements such as the members list and the menu isn't getting the simply dark colors applied

**To Reproduce:**
No idea as the fact I'm not seeing more issue's being reported means it's likely just me. Any ideas or help greatly appreciated.

**Screenshots**
![SimplyDarkSG](https://user-images.githubusercontent.com/67266376/86202345-52b7da00-bba5-11ea-9d90-68761a6f5d7a.png)

**Desktop:**
Discord channel: (Stable)
OS: (Windows)

**Additional context:**
Made sure to turn off all my plugins as to check nothing was interfering but no such luck. And I have no other themes even installed.

**Comment by Gibbu** [comment]
I'll do a quick fix soon as SimplyDark is currently being reworked with a new "colour" system. So instead of using the RGB syntax I'm swapping it to HSL syntax.

**Comment by Gibbu** [comment]
Fixed.
