### ISSUE TITLE
[BUG] Horizontal Serverlist - Scrollbar

### ISSUE THREAD

**Issue by derrobin154** [Gibbu/BetterDiscord-Themes#72]
**Describe the bug**
Because of the scrollbar you can't see where you got a message on the first servers.

**Comment by Gibbu** [comment]
HSL doesn't cause the scrollbar to be visible. At least not on my end.

**Comment by derrobin154** [comment]
It could also be the Simply Dark Design, it would be great if the upper scrollbar is not visible.

**Comment by Gibbu** [comment]
Fixed.
