### ISSUE TITLE
[BUG] MinimalCord - Search results panel not themed in the latest Discord update

### ISSUE THREAD

**Issue by kamekku14** [Gibbu/BetterDiscord-Themes#74]
**Describe the bug**
When querying the result in the search bar, the search results panel, shockingly, hasn't themed for a while.

**To Reproduce**
1. Enable MinimalCord
2. Type something in the search bar
3. Press Enter

**Screenshots**
![image](https://user-images.githubusercontent.com/66167734/87071880-7a660c80-c24d-11ea-87d3-c02c358c7d13.png)

**Desktop (please complete the following information):**
Discord channel: Stable 63045 (362a94e)
OS: Windows 10 Pro 1909, Build 18363\.900

**Comment by Gibbu** [comment]
Fixed
