### ISSUE TITLE
Profile pictures become gray when the user goes offline.

### ISSUE THREAD

**Issue by Frorran** [Gibbu/BetterDiscord-Themes#77]
![DiscordCanary_2020-07-24_13-48-55](https://user-images.githubusercontent.com/52937775/88388243-6b866a80-cdb4-11ea-9664-39d8beb837b1.jpg)

**Comment by Gibbu** [comment]
That is a weird bug. Sadly I cannot reproduce.
![image](https://user-images.githubusercontent.com/20338746/88402118-02334580-ce0e-11ea-8d37-6175d7be6adb.png)

**Comment by RealArcanePhysics** [comment]
I'm having the same issue, and it goes away when I turn off my other theme(Dark Discord). It also just started happening today, and I've been using Dark Discord and your Radial Status for almost a month now
