### ISSUE TITLE
[BUG] Slate - Go Live pop-out looks broken

### ISSUE THREAD

**Issue by forkiesassds** [Gibbu/BetterDiscord-Themes#79]
**Describe the bug**
The Go Live pop-out looks broken

**To Reproduce**
Step 1 (Optional): Start streaming
Step 2: Hover over a user that is streaming
Step 3: You see it's broken

**Screenshots**
![image](https://user-images.githubusercontent.com/54495659/89664590-0ec09f00-d8e0-11ea-91bf-8983d257afd6.png)

**Desktop (please complete the following information):**
Discord channel: Stable
OS: Windows

**Comment by Gibbu** [comment]
Hmmm... I can't really do anything about this. Discord doesn't provide any difference between streaming and playing a game.
So if I change something for streaming it will affect those who are just playing a game.

**Comment by Gibbu** [comment]
Finally fixed.
