### ISSUE TITLE
[Adjustable Server Width] "NEW" notification text is shown incorrectly with custom width

### ISSUE THREAD

**Issue by HalfOfAKebab** [Gibbu/BetterDiscord-Themes#8]
In vanilla Discord, when you have lots of servers, and there's one off-screen that has a notification, there is a red "NEW" notification at the bottom of the screen on the server list. With a custom width, this notification shows when it would normally, without checking if the affected server is actually on screen.

Here's a screenshot to show what I mean:
![NEW](https://user-images.githubusercontent.com/23153864/54554964-a05b0400-49ad-11e9-8306-e151cc4939b8.png)

The "NEW" text is shown (for the server with the yellow icon) because Discord thinks it's off-screen, even though it's not.

**Comment by Gibbu** [comment]
Hm... It seems it's a problem with discord and their height calculations and when to display the "new" notification. With the size variable anything under 40px (`--ASW_size: 40px;`) will always display the notification.
But the "new" notification at the top is not affected....
