### ISSUE TITLE
[BUG] MinimalCord - Message background problem

### ISSUE THREAD

**Issue by notLeM** [Gibbu/BetterDiscord-Themes#80]
**Describe the bug**
The message background does not have a drop shadow, nor are its corners rounded.

**To Reproduce**
Go into any server or DM.

**Screenshots**
Light Theme:
![image](https://user-images.githubusercontent.com/37753633/89730629-c10f7800-da40-11ea-860a-2d9767078b19.png)
Dark Theme;
![image](https://user-images.githubusercontent.com/37753633/89730680-4561fb00-da41-11ea-9ec6-7c4739c15032.png)

**Desktop:**
Discord channel: Stable 64952 (f65e21b)
OS: Windows 10 64-Bit (10.0.18363)

**Comment by Gibbu** [comment]
This is not a bug. Due to Discords changes to their message structure when they release the new chat design that wasn't made possible.
