### ISSUE TITLE
[BUG] MinimalCord - RPC issue in light theme

### ISSUE THREAD

**Issue by notLeM** [Gibbu/BetterDiscord-Themes#81]
**Describe the bug**
The text of the `Details` field (first one after the title) is completely white, making it invisible in Light Theme.

**To Reproduce**
Enable Light Theme and open the popout of any user with RPC on.

**Screenshots**
![image](https://user-images.githubusercontent.com/37753633/89730732-e05ad500-da41-11ea-9626-2939bb286b56.png)

**Desktop (please complete the following information):**
Discord channel: 64952 (f65e21b)
OS: Windows 10 64-Bit (10.0.18363)

**Additional context**
This issue does not appear in the full user profile.

**Comment by Gibbu** [comment]
Fixed
