### ISSUE TITLE
[BUG] Slate - Krisp menu doesnt feel right 

### ISSUE THREAD

**Issue by Aniperk** [Gibbu/BetterDiscord-Themes#82]
<img width="1017" alt="Screen Shot 2020-08-12 at 12 32 00" src="https://user-images.githubusercontent.com/32599075/90053503-d3cfba00-dc97-11ea-8cdc-778af6787b57.png">
**Describe the bug**
*((A clear and concise description of what the bug is))*

**To Reproduce**
turn on krisp

**Screenshots**
*((If applicable, add screenshots to help explain your problem))*

**Desktop (please complete the following information):**
Discord channel: Stable
OS: Macintosh

**Additional context**
*((Add any other context about the problem here.))*

**Comment by Gibbu** [comment]
Will be fixed soon. Currently busy with other things.

**Comment by Gibbu** [comment]
Fixed.

**Comment by Aniperk** [comment]
thanks
