### ISSUE TITLE
[BUG] Slate - Attach Files Button is offset incorrectly

### ISSUE THREAD

**Issue by Hsinto** [Gibbu/BetterDiscord-Themes#83]
**Describe the bug**
As title says

**To Reproduce**
*((Steps to reproduce the behavior))*

**Screenshots**
![image](https://user-images.githubusercontent.com/69600719/90054206-82c8c180-dca9-11ea-8da6-6080286c57b0.png)

**Desktop (please complete the following information):**
Discord channel: Stable
OS: Windows

**Additional context**
*((Add any other context about the problem here.))*

**Comment by Gibbu** [comment]
Will be fixed soon. Currently busy with other things.

**Comment by Gibbu** [comment]
Fixed.
