### ISSUE TITLE
[BUG] (Horizontal Server List) - (Channel notification indicator breaks with 2 monitors)

### ISSUE THREAD

**Issue by qwuzzy** [Gibbu/BetterDiscord-Themes#84]
**Describe the bug**
When I have Discord in fullscreen with HSL enabled, the half-circle to the left of the channels seeps through to my second monitor.

**To Reproduce**
I just fullscreen discord on my second monitor.

**Screenshots**
You can see this on the right of the screen.
![image](https://user-images.githubusercontent.com/32120669/90348072-f855ca00-dfe8-11ea-942f-0ca248f076f1.png)

**Desktop:**
Discord channel: Stable
OS: Windows

**Comment by Gibbu** [comment]
That's just how Discord works. To fix it you need to put your Discord in fullscreen and not maximized.
Press `CTRL` + `SHIFT` + `f`

**Comment by qwuzzy** [comment]
Wack, okay. Thank you.
