### ISSUE TITLE
[BUG] (Slate) - (Can't click on "Watch Stream")

### ISSUE THREAD

**Issue by morytain** [Gibbu/BetterDiscord-Themes#87]
**Describe the bug**
*You can't click on "Watch Stream" when someone is streaming when you hover on their name*

**To Reproduce**
*When you hover on their profile, the "Watch Stream" button is right beside the Roles bar*

**Screenshots**
*https://i.imgur.com/d7064DA.png)*

**Desktop (please complete the following information):**
Discord channel: (Stable)
OS: (Windows)

**Comment by Gibbu** [comment]
Fixed
