### ISSUE TITLE
[BUG] Emoji Background bug

### ISSUE THREAD

**Issue by IsThisMouse** [Gibbu/BetterDiscord-Themes#88]
When I click on emoji and the backgrounds pop out, its invisible and its kinda hard for me to read the emoji's name, please fix the issue

[](https://gyazo.com/8045b00b496000cb3091cfe6fae1ef10)

**Comment by Gibbu** [comment]
I created a template for a reason.
You didn't provide any valuable information.

What theme?
Where on Discord?
What is your Discord build?
What is your OS?

**Comment by abUwUser** [comment]
^ also add a screenshot. It's not required, but it can help us

**Comment by Tropix126** [comment]
closed because commenter didnt specify.
