### ISSUE TITLE
[BUG] Frosted Glass - Custom CSS text is offset

### ISSUE THREAD

**Issue by Hi-ImKyle** [Gibbu/BetterDiscord-Themes#89]
**Describe the bug**
The Custom CSS text is offset from the selection/typing

**To Reproduce**
Enable Frosted Glass, use the Custom CSS to add/change something. Notice it's offset.

**Screenshots**
![image](https://user-images.githubusercontent.com/25551312/91663605-cf056580-eae1-11ea-9ec2-f330ee5e3f6a.png)
As you can see in the image, the 2 rounded boxes are actually trying to highlight the brackets of `url("")` because the text is visually smaller in width than what the width is supposed to be?

**Desktop (please complete the following information):**
Discord channel: Stable
OS: Windows

**Additional context**
Note that I've changed the font of my installation to [Ubuntu](https://fonts.google.com/specimen/Ubuntu?query=Ubuntu), much cleaner imo, but the issue still occurs even with the default font of Frosted Glass.

**Comment by Hi-ImKyle** [comment]
**Additional Screenshot**
![](https://i.imgur.com/tef7vb0.gif)
*Note: My background image is different to the default Frosted Glass which is why it looks different.*

**Comment by Gibbu** [comment]
I cannot reproduced. What are you using to change the font?
![image](https://user-images.githubusercontent.com/20338746/91663783-685a6900-eb2e-11ea-9252-006890e180c6.png)

**Comment by Hi-ImKyle** [comment]
The font didn't matter on my end, the issue happened with only Frosted Glass enabled too. But I just did a fresh reboot of Discord and it's fine now so I'm assuming a theme of mine that I disabled earlier stook around somehow. My bad.
