### ISSUE TITLE
[SDD] "No mic input detected" message's X button is blocked by Discord's X button

### ISSUE THREAD

**Issue by HalfOfAKebab** [Gibbu/BetterDiscord-Themes#9]
The button to close the message is unclickable because it's behind Discord's X button:
![Capture](https://user-images.githubusercontent.com/23153864/54861284-a2f78980-4d1e-11e9-8343-4efea90c1695.PNG)

**Comment by HalfOfAKebab** [comment]
Also affects the Streamer Mode message

**Comment by Gibbu** [comment]
Fixed :)
