### ISSUE TITLE
[BUG] Slate - Popups are Partially Hidden

### ISSUE THREAD

**Issue by Ryonez** [Gibbu/BetterDiscord-Themes#90]
**Describe the bug**
Popups are Partially Hidden

**To Reproduce**

1. Join a voice channel
2. Click the "krisp", or "Connection Health" (RTC Info). These always has this issue.

**Screenshots**
Krisp:
![image](https://user-images.githubusercontent.com/16157130/91758915-da14de80-ec24-11ea-8320-48ce38bcd096.png)
Connection Health:
![image](https://user-images.githubusercontent.com/16157130/91759221-658e6f80-ec25-11ea-859a-887c0869577c.png)

**Desktop (please complete the following information):**
Discord channel: Stable
OS: Windows

**Comment by Tropix126** [comment]
Just found the root issue. Will be fixed next time I push changes.

**Comment by Ryonez** [comment]
Could you maybe close this when you push those changes from the commit please? It's is a currently valid issue until it's fixed, and github defaults to open issues in searches.

Info on how is here, just in case you weren't awear of it (I just looked it up and learned how myself, as I've only seen it done, not how it's done).
