### ISSUE TITLE
[BUG] (Slate) Userpopout gets cut off

### ISSUE THREAD

**Issue by sleighttt** [Gibbu/BetterDiscord-Themes#91]
![DiscordCanary_FMq3lMjGT7](https://user-images.githubusercontent.com/26939671/91790415-9d65ca80-ebc5-11ea-866d-b15033ca3f46.png)

It gets cut off when you lower on the screen. When you click the profile higher it popouts just fine. I am on Discord canary on Windows if that helps.

**Comment by Ryonez** [comment]
Already reported, but closed as it *will be fixed*, re: #90

**Comment by Tropix126** [comment]
> Already reported, but closed as it _will be fixed_, re: #90

Bug described here is entirely different. I pushed changes yesterday to fix the RTC popout. This has to do more with overflow and how JS calculates where user popouts will appear. I'll look into it, though I can't promise a fix.

**Comment by Ryonez** [comment]
Ah my mistake. It looks the same to me, being the popup border extends down past the window border in both cases.
