### ISSUE TITLE
[BUG] Horizontal Server List - Temporary Fix for Non-Default BD-Themes

### ISSUE THREAD

**Issue by KitsuneOori** [Gibbu/BetterDiscord-Themes#92]
The horizontal server list resizes itself when the server icon sizes are changed or the icon spacing is changed, cutting off the ability to see server notifications other than the @mention notification. I found a workaround for Non-BD themes which involved replacing the code on line 4 of the HSL/base.css:

	--server-container: calc(var(--server-size) + 20px);

with:

	--server-container: calc(var(--server-size) + 30px);

[Before and After](https://imgur.com/a/tabbMIz)

I hope this information helps in any way.

**Comment by Gibbu** [comment]
That's just a issue with your theme displaying the server list scrollbar.

**Comment by KitsuneOori** [comment]
On the contrary. If I were to minimize some folders and get rid of the scrollbar, the notifications wouldn't appear. My screenshots made it seem that way.

**Comment by Gibbu** [comment]
Seems like a theme issue.

Neutron by Spectra.
My guess is the way he did the titlebar is messing with it.
![image](https://user-images.githubusercontent.com/20338746/92492909-40a68780-f237-11ea-95f2-c34e3c210c31.png)

Default
![09-00 50 - Wednesday - 1599576601](https://user-images.githubusercontent.com/20338746/92492522-c413a900-f236-11ea-8c89-ab4bdf1ac331.png)

SimplyDark by me
![09-00 50 - Wednesday - 1599576635](https://user-images.githubusercontent.com/20338746/92492528-c544d600-f236-11ea-8374-9bb880da58aa.png)

Forsted Glass by me
![09-00 51 - Wednesday - 1599576693](https://user-images.githubusercontent.com/20338746/92492529-c5dd6c80-f236-11ea-8122-a79a47d618a8.png)

BasicBackground by DevilBro
![09-00 52 - Wednesday - 1599576730](https://user-images.githubusercontent.com/20338746/92492531-c6760300-f236-11ea-85ee-4f8336d85ecb.png)

**Comment by Tropix126** [comment]
forsted glass KEKW

**Comment by Tropix126** [comment]
Also if your theme heavily modifies the guilds list, HSL will end up breaking.
