### ISSUE TITLE
No GIFs button or Gifts button

### ISSUE THREAD

**Issue by TurtleTrademark** [Gibbu/BetterDiscord-Themes#95]
The buttons work when the theme is off, but not when the theme is on. 
![image](https://user-images.githubusercontent.com/71402796/95110027-6d04d500-070b-11eb-89e9-f4dc9c8b1764.png)
![image](https://user-images.githubusercontent.com/71402796/95110083-80b03b80-070b-11eb-98d8-156812e78e66.png)

**Comment by Gibbu** [comment]
Open the theme and enable them.
![image](https://user-images.githubusercontent.com/20338746/95110265-7af93b00-0789-11eb-9b37-73e2a98bbfd4.png)

Also this repo is no longer in use.
Current repo: https://github.com/DiscordStyles/FrostedGlass
